### ISSUE TITLE
Paypal donation error in sandbox.

### ISSUE THREAD

**Issue by nicnacnic** [esamarathon/oengusio#44] opened 2021-03-20 01:57 UTC
### Describe the bug

When donating from sandbox with Paypal sandbox accounts, Oengus gives an error after the donation has supposedly been processed by Paypal, and doesn't appear in the tracker.
Unknown if this also affects production.
Donating from a US Paypal sandbox account on a sandbox marathon (the payee is also a sandbox account!)

### How to reproduce

1. Create a marathon on Oengus sandbox. When enabling donations, enter a Paypal sandbox email address for the payee.
2. Start a donation from another Paypal sandbox account. It can be any amount.
3. After the donation has been processed by Paypal, Oengus redicts you back to the donations page and gives a generic error. In the console, it's status code 500 (internal server error).

### Expected behavior

The donation should go through normally and change donation total/incentive totals.

### Desktop (please complete the following information)

- OS: Windows 10
- Browser: Chrome
- Version: 89.0.4389.90

Chrome console error.
![image](https://user-images.githubusercontent.com/39160563/111855801-09f3ad00-88fd-11eb-92b1-f17581841cc9.png)

**Comment by duncte123** [comment] 2021-03-20 08:19
Duplicate of #14

**Closed by duncte123** 2021-03-20 08:19 UTC
Labels: bug
